apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx2
spec:
  selector:
    matchLabels:
      app: my-nginx2
  replicas: 2
  template:
    metadata:
      labels:
        app: my-nginx2
    spec:
      containers:
      - name: my-nginx2
        image: nginx
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: my-service2
spec:
  selector:
    app: my-nginx2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
