apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx3
spec:
  selector:
    matchLabels:
      run: my-nginx3
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx3
    spec:
      containers:
      - name: my-nginx3
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx3
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: my-nginx3
  type: NodePort
