apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hello-minik8
  name: hello-minik8
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello-minik8
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hello-minik8
    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.4
        imagePullPolicy: IfNotPresent
        name: hello-mini8
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: minik8-service
spec:
  selector:
    run: hello-minik8
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer

